name: Build and Release Dictionary

on:
  workflow_dispatch:
  push:
    paths:
      - '**.tsv'
      - 'conv_dict/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
        actions: write
        checks: write
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run dictionary converter
        id: build
        run: |
          # pip install -r requirements.txt || true
          python conv_dict/conv_dict.py

      - name: Get ZIP filename
        id: get-zip
        run: |
          ZIP_FILE=$(ls output/*.zip | sort | tail -n 1)
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "tag_name=$(basename $ZIP_FILE .zip)" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.get-zip.outputs.tag_name }}
          git push origin ${{ steps.get-zip.outputs.tag_name }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-zip.outputs.tag_name }}
          name: ${{ steps.get-zip.outputs.tag_name }}
          files: ${{ steps.get-zip.outputs.zip_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}